### ISSUE TITLE
Linked issue doesn't exist

### ISSUE THREAD

**Issue by techtonik** [badges/shielded#6]
Project title references https://github.com/olivierlacan/shields/issues/15?source=c which is 404

**Comment by nathany** [comment]
Possibly it is referring to https://github.com/badges/shields/issues/15?

**Comment by techtonik** [comment]
Why not just state the purpose clearly? =)

**Comment by nathany** [comment]
Afaik this repo is deprecated, please refer to https://github.com/badges/shields instead.

**Comment by techtonik** [comment]
Do you mean https://github.com/badges/shielded is deprecated?

**Comment by nathany** [comment]
Yes.
